# Generated by Django 3.0.7 on 2020-07-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInsert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('company_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobInsert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default='', max_length=50)),
                ('company_name', models.CharField(default='', max_length=100)),
                ('jobtype', models.CharField(default='', max_length=50)),
                ('location', models.CharField(default='', max_length=100)),
                ('job_description', models.TextField(default='', max_length=1000)),
                ('qualifications', models.TextField(default='', max_length=1000)),
                ('additional_info', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserInsert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=11)),
                ('Address', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='media/%Y/%m/%d')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='UserResumes',
            fields=[
                ('Resume_ID', models.AutoField(primary_key=True, serialize=False)),
                ('pinfo', models.CharField(default='', max_length=1000)),
                ('cgpa', models.CharField(default='', max_length=50)),
                ('mobile', models.CharField(default='', max_length=11)),
                ('email', models.CharField(default='', max_length=50)),
                ('objective', models.CharField(default='', max_length=1000)),
                ('education', models.TextField(default='', max_length=5000)),
                ('skill', models.TextField(default='', max_length=5000)),
                ('achievements', models.CharField(default='', max_length=3000)),
                ('projects', models.TextField(default='', max_length=5000)),
                ('hobbies', models.CharField(default='', max_length=1000)),
            ],
            options={
                'db_table': 'resumeparser',
            },
        ),
    ]
