# Generated by Django 3.0.7 on 2020-07-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_demo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobinsert',
            old_name='jobtype',
            new_name='job_type',
        ),
        migrations.AddField(
            model_name='demo',
            name='mobile_number',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='userresumes',
            name='FirstName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userresumes',
            name='LastName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyinsert',
            name='company_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyinsert',
            name='designation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyinsert',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyinsert',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='companyinsert',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='companyinsert',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyinsert',
            name='phone_number',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='jobinsert',
            name='additional_info',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='userinsert',
            name='Address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinsert',
            name='Email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinsert',
            name='FirstName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinsert',
            name='LastName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinsert',
            name='PhoneNumber',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='userinsert',
            name='document',
            field=models.FileField(default='', upload_to='media/%Y/%m/%d'),
        ),
        migrations.AlterModelTable(
            name='companyinsert',
            table='recruiter_companyinsert',
        ),
        migrations.AlterModelTable(
            name='demo',
            table='recruiter_demo',
        ),
        migrations.AlterModelTable(
            name='jobinsert',
            table='recruiter_jobinsert',
        ),
    ]
